import {setupSpaceTools} from './src/space-tools.js';
import {attachmentIssue} from './src/space-model.js';
import { catalog,initialState,footprint,moveItem,rotateItem,addItem,validState,serializePlan,placementIssue } from './src/editor-model.js';
import { palettes } from './src/geometry.js';
import { interview,getDemoReply } from './src/design-guide.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state=initialState(),selected=null,scene=null,history=[],future=[],brief={},messages=[],busy=false,started=false,liveAI=false,toastTimer,view='3d';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const saved=JSON.parse(localStorage.getItem('iv-corners-studio-v2'));if(validState(saved?.state)){state=saved.state;brief=Object.fromEntries(Object.entries(saved.brief||{}).filter(([k,v])=>interview.some(q=>q.key===k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,500)]));$('#save-status').textContent='Your saved room is ready.'}}catch{}
function toast(message){clearTimeout(toastTimer);$('#room-toast').hidden=false;$('#room-toast').textContent=message;toastTimer=setTimeout(()=>$('#room-toast').hidden=true,4500)}
function commit(next){history.push(structuredClone(state));if(history.length>40)history.shift();future=[];state=next;render();$('#save-status').textContent='Unsaved changes · saved only on this device';}
function select(id){selected=id;scene?.select(id);renderSelection()}
function renderSelection(){const item=state.items.find(x=>x.id===selected);$('#selection-toolbar').hidden=!item||view==='eye';if(item){$('#rotation-angle').value=item.rotation;$('#rotation-value').textContent=`${Math.round(item.rotation)}°`;$('#selected-name').textContent=item.name;$('#selected-size').textContent=`${Math.round(item.w*12)} × ${Math.round(item.d*12)} in`}$$('#inventory-list button').forEach(b=>b.classList.toggle('selected',b.dataset.id===selected));}
function handleMove(id,x,z){const result=moveItem(state,id,x,z);if(result.ok){const old=state.items.find(p=>p.id===id),next=result.state.items.find(p=>p.id===id);if(old.x!==next.x||old.z!==next.z)commit(result.state);else scene?.update(state)}else{scene?.update(state);toast(result.reason)}select(id)}
function add(kind,point){const result=addItem(state,kind);if(!result.ok){toast(result.reason);return false}let next=result.state;if(point){const piece=next.items.find(x=>x.id===result.id),f=footprint(piece);const moved=moveItem(next,result.id,point.x-f.w/2,point.z-f.d/2);if(moved.ok)next=moved.state;else toast('Placed in an open spot. The drop position was blocked.')}commit(next);select(result.id);return true}
function render(){
 if(scene)scene.update(state);else $('#room-canvas').innerHTML=`<div class="room-fallback">${serializePlan(state)}</div>`;
 $('#project-name').textContent=state.room.name;$('#room-heading').textContent=state.room.name==='My next chapter'?'The living room.':state.room.name;$('#dimensions-label').textContent=`${+state.room.width.toFixed(2)}′ × ${+state.room.depth.toFixed(2)}′`;$('#current-palette').textContent=palettes[state.palette].name;
 $('#room-swatches').innerHTML=palettes[state.palette].materials.slice(0,4).map(m=>`<img src="/assets/${m[0]}.jpg" alt="${m[1]}" title="${m[1]}">`).join('');
 $('#piece-count').textContent=`${state.items.length} pieces`;$('#inventory-list').replaceChildren();for(const item of state.items){const b=document.createElement('button');b.textContent=item.name;b.dataset.id=item.id;b.addEventListener('click',()=>{select(item.id);$('#room-canvas').focus()});$('#inventory-list').append(b)}
 $('#undo').disabled=!history.length;$('#redo').disabled=!future.length;renderSelection();
}
function thumb(kind){const shapes={sofa:'<path d="M7 44h85v24H7z" fill="#bbab91"/><path d="M11 24h77v27H11z" fill="#d1c2a7"/><path d="M7 36h9v27H7zm76 0h9v27h-9" fill="#9e8a70"/><path d="M41 27v26m24-26v26M17 53h65" fill="none" stroke="#a9977f"/><path d="M14 68v7m71-7v7" stroke="#674d38" stroke-width="4"/>',chair:'<path d="m23 26 44-5 5 36-43 8Z" fill="#a18b6d"/><path d="M27 30h34v24H27z" fill="#cbbda3"/><path d="m20 48 8-3 5 20-8 4zm46-7 9-1 1 25-8 3z" fill="#715942"/><path d="M28 63v16m40-15v12" stroke="#715942" stroke-width="4"/>',table:'<ellipse cx="50" cy="60" rx="15" ry="10" fill="#a28c6f"/><path d="M35 33h30v27H35z" fill="#b7a58b"/><ellipse cx="50" cy="33" rx="39" ry="17" fill="#d3c3aa"/><path d="M11 33v4c7 20 70 20 78 0v-4" fill="#c1af94"/>',sideboard:'<path d="m9 31 76-9 9 10-77 9Z" fill="#a0805e"/><path d="M17 41 94 32v36l-77 9Z" fill="#775339"/><path d="m9 31 8 10v36l-8-10Z" fill="#60452f"/><path d="M40 38v35m27-38v35" stroke="#513722"/>',rug:'<path d="m6 56 35-32 54 19-31 32Z" fill="#c3b397"/><path d="m14 55 28-24 44 15-24 22Z" fill="none" stroke="#e2d3b8" stroke-width="2"/>',plant:'<path d="M33 53h35l-6 29H40Z" fill="#b38a6b"/><path d="M50 59V20" stroke="#796847" stroke-width="3"/><ellipse cx="37" cy="31" rx="12" ry="19" transform="rotate(-35 37 31)" fill="#74815a"/><ellipse cx="63" cy="26" rx="11" ry="19" transform="rotate(30 63 26)" fill="#889667"/><ellipse cx="45" cy="15" rx="10" ry="16" fill="#65764f"/>',lamp:'<ellipse cx="50" cy="81" rx="20" ry="5" fill="#9c8257"/><path d="M50 27v54" stroke="#aa8e59" stroke-width="3"/><path d="m32 10-12 25h60L68 10Z" fill="#d8c8a5"/><ellipse cx="50" cy="35" rx="30" ry="7" fill="#c2af88"/>'};return `<svg viewBox="0 0 100 95" aria-hidden="true">${shapes[kind]}</svg>`}
function renderCatalog(filter='all'){$('#furniture-catalog').replaceChildren();for(const piece of catalog.filter(p=>filter==='all'||p.category===filter)){const button=document.createElement('button');button.className='furniture-card';button.draggable=true;button.dataset.kind=piece.kind;button.setAttribute('aria-label',`Add ${piece.name.toLowerCase()}, ${piece.note}`);button.innerHTML=`<span class="furniture-thumbnail">${piece.thumbnail?`<img src="${piece.thumbnail}" alt="" loading="lazy">`:thumb(piece.kind)}<span class="add-indicator">+</span></span><strong>${piece.name}</strong><small>${piece.note}</small>`;button.addEventListener('click',()=>{if(add(piece.kind)){toast(`${piece.name} added. Drag it into place.`);if(innerWidth<=900)closeDrawers()}});button.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/iv-furniture',piece.kind);e.dataTransfer.effectAllowed='copy'});$('#furniture-catalog').append(button)}}
function syncDrawers(){for(const id of ['collection-panel','airena-panel']){const el=$('#'+id);const hidden=(id==='collection-panel'?innerWidth<=900:innerWidth<=650)&&!el.classList.contains('drawer-open');el.inert=hidden;el.setAttribute('aria-hidden',String(hidden));}}
function closeDrawers(){$$('.drawer-open').forEach(p=>p.classList.remove('drawer-open'));$('#drawer-backdrop').hidden=true;$$('[data-drawer]').forEach(b=>b.classList.remove('active'));syncDrawers();}
function openDrawer(id){closeDrawers();if(id==='room')return;$('#'+id).classList.add('drawer-open');$('#drawer-backdrop').hidden=false;$$(`[data-drawer="${id}"]`).forEach(b=>b.classList.add('active'));syncDrawers();if(id==='airena-panel')startConversation();}
$$('[data-drawer]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.drawer)));$$('[data-close-drawer]').forEach(b=>b.addEventListener('click',closeDrawers));$('#drawer-backdrop').addEventListener('click',closeDrawers);
$('#undo').addEventListener('click',()=>{if(!history.length)return;future.push(structuredClone(state));state=history.pop();render();$('#save-status').textContent='Unsaved changes'});$('#redo').addEventListener('click',()=>{if(!future.length)return;history.push(structuredClone(state));state=future.pop();render();$('#save-status').textContent='Unsaved changes'});
$('#rotate-item').addEventListener('click',()=>{const r=rotateItem(state,selected,45);r.ok?commit(r.state):toast(r.reason)});$('#remove-item').addEventListener('click',()=>{if(!selected)return;const id=selected;selected=null;commit({...state,items:state.items.filter(p=>p.id!==id)})});
$('#room-canvas').addEventListener('keydown',e=>{if(view==='eye'){const action={ArrowUp:'forward',w:'forward',ArrowDown:'back',s:'back',ArrowLeft:'turn-left',a:'left',ArrowRight:'turn-right',d:'right'}[e.key];if(action){e.preventDefault();scene?.walk(action)}return;}if(!selected)return;const piece=state.items.find(x=>x.id===selected);if(!piece)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=e.shiftKey?1:.25;handleMove(selected,piece.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0),piece.z+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0))}if(e.key.toLowerCase()==='r')$('#rotate-item').click();if(['Delete','Backspace'].includes(e.key)){e.preventDefault();$('#remove-item').click()}});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;$$('[data-view]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-selected',active);x.tabIndex=active?0:-1});scene?.setMode(view);$('#walk-controls').hidden=view!=='eye';$('#selection-toolbar').hidden=view==='eye'||!selected;$('#room-canvas').focus();$('#canvas-help').textContent=view==='eye'?'Drag to look · Arrows or buttons to move · Preview only':view==='3d'?'Drag furniture to move · Drag empty space to orbit · Scroll to zoom':'Drag furniture to move · Select a piece to rotate or remove'}));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-selected',active);x.tabIndex=active?0:-1});renderCatalog(b.dataset.filter)}));
$$('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=[...list.querySelectorAll('[role=tab]')],i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus()}));
$('#reset-camera').addEventListener('click',()=>scene?.resetCamera());$('#cycle-palette').addEventListener('click',()=>commit({...state,palette:(state.palette+1)%3}));$('#inventory-toggle').addEventListener('click',()=>{const list=$('#inventory-list');list.hidden=!list.hidden;$('#inventory-toggle').setAttribute('aria-expanded',!list.hidden)});
$('#edit-dimensions').addEventListener('click',()=>{$('#project-input').value=state.room.name;$('#width-input').value=+state.room.width.toFixed(2);$('#depth-input').value=+state.room.depth.toFixed(2);$('#custom-shape-option').hidden=state.room.shape!=='custom';$('#shape-input').value=state.room.shape;$('#room-settings').showModal()});
function setDimensions(width,depth,shape=state.room.shape,name=state.room.name){if(![width,depth].every(v=>Number.isFinite(v)&&v>=4&&v<=60)){toast('Choose dimensions between 4 and 60 feet.');return false}const room={name,width,depth,shape,height:state.room.height||8};if(shape==='custom'){if(!state.room.vertices)return false;room.vertices=state.room.vertices.map(p=>({x:p.x*width/state.room.width,z:p.z*depth/state.room.depth}));}const next={...state,room};if(shape!==state.room.shape){next.openings=[];next.artworks=[];}else{next.openings=(state.openings||[]).filter(p=>!attachmentIssue(room,p));next.artworks=(state.artworks||[]).filter(p=>!attachmentIssue(room,p));}const removed=next.items.filter(item=>placementIssue({...next,items:[]},item));next.items=next.items.filter(item=>!removed.includes(item));commit(next);if(removed.length)toast(`${removed.length} pieces returned to the collection to fit the new room.`);return true}
$('#dimensions-form').addEventListener('submit',e=>{e.preventDefault();if(setDimensions(+$('#width-input').value,+$('#depth-input').value,$('#shape-input').value,$('#project-input').value.trim()||'My next chapter'))$('#room-settings').close()});
$('#save-project').addEventListener('click',()=>{try{localStorage.setItem('iv-corners-studio-v2',JSON.stringify({state,brief}));$('#save-status').textContent='Saved on this device · just now';toast('Your room and design brief are saved on this device.')}catch{toast('Your browser could not save this room. Export your plan instead.')}});
$('#export-project').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([serializePlan(state)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='iv-corners-my-room.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your current arrangement has been exported.')});
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#connection-settings').addEventListener('click',()=>$('#connections-dialog').showModal());$('#live-call').addEventListener('click',()=>$('#connections-dialog').showModal());$('#continue-chat').addEventListener('click',()=>{$('#connections-dialog').close();if(innerWidth<=650)openDrawer('airena-panel');startConversation();$('#chat-input').focus()});
addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawers()});
function updateProgress(){const count=interview.filter(q=>brief[q.key]).length;$('#brief-count').textContent=`${count} / 8`;$('#brief-progress-bar').style.width=`${count/8*100}%`}
function choices(values){$('#suggestion-choices').replaceChildren();values.slice(0,3).forEach(value=>{const b=document.createElement('button');b.textContent=value;b.addEventListener('click',()=>send(value));$('#suggestion-choices').append(b)})}
function scrollChat(){$('#chat-log').scrollTop=$('#chat-log').scrollHeight}
async function message(role,text,animate=true){const el=document.createElement('article');el.className=`chat-message ${role}`;const speaker=document.createElement('div');speaker.className='speaker';speaker.textContent=role==='user'?'YOU':'AIRENA';const p=document.createElement('p');el.append(speaker,p);$('#chat-log').append(el);if(role==='assistant'&&animate&&!reduced){p.setAttribute('aria-hidden','true');const accessible=document.createElement('span');accessible.className='sr-only';accessible.textContent=text;el.append(accessible);for(let i=0;i<text.length;i+=8){p.textContent=text.slice(0,i+8);scrollChat();await new Promise(r=>setTimeout(r,12))}p.removeAttribute('aria-hidden');accessible.remove()}else p.textContent=text;scrollChat();return el}
async function startConversation(){if(started)return;started=true;busy=true;$('#chat-send').disabled=true;const next=interview.find(q=>!brief[q.key]);await message('assistant',`Hello, I’m AIrena. Think of me as another pair of eyes for your space.\n\n${next?next.question:'Welcome back. Your design brief is saved. What would you like to try next?'}`);choices(next?.choices||['Add a plant','Try a warmer palette','Add a chair']);busy=false;$('#chat-send').disabled=false;}
$('#meet-airena').addEventListener('click',async()=>{if(!started)await startConversation();else $('#chat-input').focus()});
function actionCard(action,parent){if(!['set_palette','add_item','set_dimensions'].includes(action.type))return;if(action.type==='set_palette'&&!['0','1','2'].includes(action.value))return;if(action.type==='add_item'&&!catalog.some(c=>c.kind===action.value))return;const card=document.createElement('div');card.className='chat-action';const title=document.createElement('p');title.textContent=action.type==='set_palette'?palettes[+action.value].name:action.type==='add_item'?catalog.find(c=>c.kind===action.value).name:'A room to your measure';card.append(title);if(action.type==='set_palette'){const swatches=document.createElement('div');swatches.className='action-swatches';palettes[+action.value].materials.slice(0,4).forEach(m=>{const img=document.createElement('img');img.src=`/assets/${m[0]}.jpg`;img.alt=m[1];swatches.append(img)});card.append(swatches)}const apply=document.createElement('button');apply.textContent=action.label||'Try this in my room ↗';apply.addEventListener('click',()=>{let ok=true;if(action.type==='set_palette')commit({...state,palette:+action.value});if(action.type==='add_item')ok=add(action.value);if(action.type==='set_dimensions'){const [w,d]=action.value.split(',').map(Number);ok=setDimensions(w,d)}if(ok){apply.textContent='Applied to your room ✓';apply.disabled=true;if(innerWidth<=650)closeDrawers();toast('Updated. You can undo this change at any time.')}});card.append(apply);parent.append(card);scrollChat()}
async function send(text){text=text.trim();if(!text||busy)return;if(!started){started=true}busy=true;$('#chat-send').disabled=true;choices([]);$('#chat-input').value='';await message('user',text,false);messages.push({role:'user',content:text});const typing=document.createElement('div');typing.className='chat-message';typing.setAttribute('aria-label','AIrena is composing a response');typing.innerHTML='<span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span>';$('#chat-log').append(typing);scrollChat();let result;
 try{if(liveAI){const response=await fetch('/.netlify/functions/airena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:messages.slice(-20),room:state.room,brief}),signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('AIrena could not connect. Please try again in a moment.');result=await response.json();}else{await new Promise(r=>setTimeout(r,reduced?0:400));result=getDemoReply(text,brief,state)}}catch(error){typing.remove();await message('assistant',error.message,false);busy=false;$('#chat-send').disabled=false;return}
 typing.remove();if(result.brief)brief={...brief,...Object.fromEntries(Object.entries(result.brief).filter(([k,v])=>interview.some(q=>q.key===k)&&typeof v==='string'&&v.trim()))};updateProgress();const el=await message('assistant',String(result.reply).slice(0,3000));messages.push({role:'assistant',content:result.reply});for(const action of (result.actions||[]).slice(0,3))actionCard(action,el);choices(result.choices||[]);if(interview.every(q=>brief[q.key])&&!$('#completed-brief')){const summary=document.createElement('div');summary.id='completed-brief';summary.className='brief-summary';const title=document.createElement('strong');title.textContent='Your design brief';summary.append(title);const dl=document.createElement('dl');for(const q of interview){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=q.title;dd.textContent=brief[q.key];dl.append(dt,dd)}summary.append(dl);el.append(summary);scrollChat()}busy=false;$('#chat-send').disabled=false;}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();send($('#chat-input').value)});$('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value)}});$('#restart-brief').addEventListener('click',()=>{if(busy)return;brief={};messages=[];started=false;$('#chat-log').replaceChildren();updateProgress();startConversation()});
$('#reference-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){toast('Choose a JPG, PNG, or WebP smaller than 10 MB.');return}const url=URL.createObjectURL(file),image=new Image();image.src=url;try{await image.decode();image.className='reference-preview';image.alt='Your inspiration reference';const el=await message('user','A reference for the feeling.',false);el.prepend(image);await message('assistant','Keep this as a reference in our conversation. I can’t analyze images in this prototype yet — what draws you to it: the colors, the textures, or the overall mood?',false);choices(['The warm colors','The quiet textures','The bold mood']);image.addEventListener('load',()=>URL.revokeObjectURL(url),{once:true});}catch{URL.revokeObjectURL(url);toast('This image could not be opened.')}e.target.value=''});
async function checkConnection(){if(['localhost','127.0.0.1'].includes(location.hostname))return;try{const res=await fetch('/.netlify/functions/airena');if(!res.ok)return;const status=await res.json();liveAI=status.configured===true;if(liveAI){$('#chat-mode').textContent='LIVE AI';$('#chat-disclosure').textContent='AI design guide · Review suggestions before applying';$('#ai-connection-state').textContent='Connected'}}catch{}}
renderCatalog();render();updateProgress();
// Keep the page useful if the GPU or the 3D module is unavailable.
try{const {createRoomScene}=await import('./src/room-scene.js');$('#room-canvas').replaceChildren();scene=createRoomScene($('#room-canvas'),{select,move:handleMove,drop:(kind,x,z)=>add(kind,{x,z})});scene.update(state)}catch(error){console.warn('Using the accessible plan fallback:',error.message);$('#room-canvas').innerHTML=`<div class="room-fallback">${serializePlan(state)}</div>`;$('#canvas-help').textContent='3D unavailable here. Use the item list and arrow keys to arrange your plan.';}
// Read-only room inspection for assistive integrations and spatial tooling.
window.ivRoom={getState:()=>structuredClone(state),projectItem:id=>scene?.projectItem(id)};
checkConnection();
const welcome=document.createElement('article');welcome.className='chat-message';welcome.innerHTML='<div class="speaker">A NOTE FROM AIRENA</div><p>A home starts with a conversation.<br>Click my portrait, and tell me what yours should feel like.</p>';$('#chat-log').append(welcome);choices(['Slow mornings & reading','Friends & hosting','Add a plant']);

if(new URLSearchParams(location.search).has("chat")){if(innerWidth<=650)openDrawer("airena-panel");else startConversation();}

syncDrawers();addEventListener('resize',syncDrawers);

// Preview a drag continuously, then record the entire gesture as one undo step.
let rotationStart=null,rotationPreview=null;
$('#rotation-angle').addEventListener('input',e=>{
 if(!selected)return;
 rotationStart??=structuredClone(state);
 const item=rotationStart.items.find(p=>p.id===selected);
 if(!item)return;
 const angle=Number(e.target.value),result=rotateItem(rotationStart,selected,angle-item.rotation);
 if(result.ok){rotationPreview=result.state;scene?.update(rotationPreview);if(!scene)$('#room-canvas').innerHTML=`<div class="room-fallback">${serializePlan(rotationPreview)}</div>`;$('#rotation-value').textContent=`${angle}°`;}
 else{toast(result.reason);const accepted=(rotationPreview||rotationStart).items.find(p=>p.id===selected).rotation;$('#rotation-value').textContent=`${Math.round(accepted)}°`;}
});
function finishRotation(){if(!rotationStart)return;const next=rotationPreview;rotationStart=null;rotationPreview=null;if(next&&JSON.stringify(next)!==JSON.stringify(state))commit(next);else render();}
$('#rotation-angle').addEventListener('change',finishRotation);
$('#rotation-angle').addEventListener('blur',finishRotation);
$('#rotation-angle').addEventListener('pointercancel',()=>{rotationStart=null;rotationPreview=null;render();});

$('#catalog-category').addEventListener('change',e=>renderCatalog(e.target.value));

const spaceTools=setupSpaceTools({getState:()=>state,commit,toast});
$('#trace-plan').onclick=()=>spaceTools.trace();$('#edit-walls').onclick=()=>spaceTools.walls();
document.querySelectorAll('[data-walk]').forEach(b=>b.addEventListener('click',()=>scene?.walk(b.dataset.walk)));
