import {wallFinishes,floorFinishes,finishesFor} from './finishes.js';
import {listLayouts,saveLayout,removeLayout} from './layout-storage.js';
const $=s=>document.querySelector(s);
export function setupDesignPanel({getState,getScene,commit,toast,restoreView}){
 document.body.insertAdjacentHTML('beforeend',`<dialog id="finishes-dialog" class="space-dialog compact-dialog" aria-labelledby="finishes-title"><header><div><p class="eyebrow">THE PALETTE OF YOUR EVERYDAY</p><h2 id="finishes-title">Find your <em>feeling.</em></h2></div><button data-design-close aria-label="Close finishes">×</button></header><p class="space-note">Try a finish, close this panel to explore, and undo any change. These are visual studies, not manufacturer paint matches.</p><h3>Wall paint</h3><div id="wall-finish-options" class="finish-options"></div><h3>Underfoot</h3><div id="floor-finish-options" class="finish-options"></div><h3>Light & atmosphere</h3><div id="light-options" class="finish-options light-options"></div><p class="space-note">Lighting presets are artistic previews, not a sun-path simulation. Catalog furniture keeps its original materials.</p><button class="solid-button" id="finish-done">See it in my room ↗</button></dialog>
 <dialog id="layouts-dialog" class="space-dialog" aria-labelledby="layouts-title"><header><div><p class="eyebrow">A LITTLE ROOM TO EXPERIMENT</p><h2 id="layouts-title">One room. <em>New possibilities.</em></h2></div><button data-design-close aria-label="Close saved layouts">×</button></header><p class="space-note">Save up to six variations with their camera views, finishes, and artwork. Compare the previews below, or restore a layout to explore it. Restoring is undoable. Layouts stay in this browser and are removed if its site data is cleared.</p><form id="save-layout-form" class="save-layout-form"><label for="layout-name">Name this version<input id="layout-name" maxlength="50" placeholder="Slow Sunday · Layout A" required></label><button class="solid-button" id="save-layout-button" type="submit">Save this layout ↗</button></form><p id="layout-feedback" role="status"></p><div id="saved-layouts" class="saved-layouts"></div></dialog>`);
 document.querySelectorAll('[data-design-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#finish-done').onclick=()=>$('#finishes-dialog').close();
 function paint(){const f=finishesFor(getState());for(const [field,values,target] of [['wall',wallFinishes,'#wall-finish-options'],['floor',floorFinishes,'#floor-finish-options'],['light',[{id:'daylight',name:'Soft daylight',color:'#e8ddc1'},{id:'evening',name:'Golden evening',color:'#b58d65'}],'#light-options']]){const root=$(target);root.replaceChildren();for(const option of values){const b=document.createElement('button');b.type='button';b.className='finish-option';b.setAttribute('aria-pressed',String(f[field]===option.id));const swatch=document.createElement('span');swatch.className='finish-chip';swatch.style.background=option.color||'#d3c7b3';const label=document.createElement('span');label.textContent=option.name;b.append(swatch,label);b.onclick=()=>{const s=getState();commit({...s,finishes:{...finishesFor(s),[field]:option.id}});paint()};root.append(b);}}}
 async function showLayouts(){const root=$('#saved-layouts');root.replaceChildren();try{const layouts=await listLayouts();if(!layouts.length){const p=document.createElement('p');p.className='layout-empty';p.textContent='Your first idea belongs here. Give the room a name above and save a version.';root.append(p);return;}for(const layout of layouts){const card=document.createElement('article');card.className='layout-card';const img=document.createElement('img');img.src=layout.preview;img.alt=`Room preview: ${layout.name}`;const title=document.createElement('h3');title.textContent=layout.name;const meta=document.createElement('p');meta.textContent=`${layout.state.items.length} pieces · ${+layout.state.room.width.toFixed(1)}′ × ${+layout.state.room.depth.toFixed(1)}′ · ${new Date(layout.created).toLocaleDateString()}`;const actions=document.createElement('div');actions.className='space-button-row';const restore=document.createElement('button');restore.textContent='Explore this layout ↗';restore.onclick=()=>{commit(structuredClone(layout.state));restoreView(layout.camera);$('#layouts-dialog').close();toast('Layout restored. Undo returns to your previous room.');};const remove=document.createElement('button');remove.textContent='Remove';let confirm=false;remove.onclick=async()=>{if(!confirm){confirm=true;remove.textContent='Confirm remove';return}try{await removeLayout(layout.id);await showLayouts()}catch(error){$('#layout-feedback').textContent=error.message}};actions.append(restore,remove);card.append(img,title,meta,actions);root.append(card);}}catch(error){$('#layout-feedback').textContent=error.message;}}
 async function capture(){const scene=getScene();if(!scene)throw Error('Image capture needs the 3D view. Your SVG floor plan can still be exported.');await scene.ready();return scene.capture();}
 $('#save-layout-form').onsubmit=async e=>{e.preventDefault();const button=$('#save-layout-button');if(button.disabled)return;button.disabled=true;$('#layout-feedback').textContent='Preparing your room preview…';try{const preview=await capture(),state=structuredClone(getState()),camera=getScene()?.getCamera();await saveLayout({id:crypto.randomUUID(),name:$('#layout-name').value.trim()||'My room',created:Date.now(),state,camera,preview});$('#layout-name').value='';$('#layout-feedback').textContent='Saved in this browser.';await showLayouts();}catch(error){$('#layout-feedback').textContent=error.message}finally{button.disabled=false}};
 return {finishes(){paint();$('#finishes-dialog').showModal()},async layouts(){$('#layout-feedback').textContent='';$('#layouts-dialog').showModal();await showLayouts()},async exportImage(){const button=$('#export-image');button.disabled=true;try{const data=await capture(),a=document.createElement('a');a.href=data;a.download='iv-corners-room-view.png';a.click();toast('Your room view has been downloaded.')}catch(error){toast(error.message)}finally{button.disabled=false}}};
}
