import {validFinishes} from './finishes.js';
import {roomPolygon,containsPolygon,validArchitecture,walls} from './space-model.js';
import { modelCatalog } from './model-catalog.js';
export const catalog = [
 ...modelCatalog,
 {kind:'sofa',name:'The linen sofa',category:'Seating',w:7,d:3,h:2.6,color:'#c6b69e',note:'84 × 36 in'},
 {kind:'chair',name:'The reading chair',category:'Seating',w:2.6,d:2.8,h:2.7,color:'#8b7158',note:'31 × 34 in'},
 {kind:'table',name:'The stone table',category:'Tables',w:3.3,d:2,h:1.25,color:'#bba88b',note:'40 × 24 in'},
 {kind:'sideboard',name:'The walnut console',category:'Storage',w:5.4,d:1.4,h:2.5,color:'#72503c',note:'65 × 17 in'},
 {kind:'rug',name:'The woven rug',category:'Finishing touches',w:8,d:6,h:.04,color:'#cbbb9e',note:'8 × 6 ft'},
 {kind:'plant',name:'A little greenery',category:'Finishing touches',w:1.6,d:1.6,h:4.1,color:'#697453',note:'19 × 19 in'},
 {kind:'lamp',name:'The floor lamp',category:'Lighting',w:1.5,d:1.5,h:5,color:'#b09361',note:'18 × 18 in'}
];
export function initialState(){return {version:2,room:{name:'My next chapter',width:16,depth:13,shape:'rectangle'},palette:0,items:[['rug',4.4,5.3],['sofa',5,9.5],['chair',1.2,6.2],['table',7,6.6],['sideboard',5.3,.45],['plant',13.5,1.3]].map(([kind,x,z],i)=>({...catalog.find(p=>p.kind===kind),x,z,id:'piece-'+i,rotation:kind==='sofa'?180:0}))};}
export function footprint(item){const a=item.rotation*Math.PI/180,c=Math.abs(Math.cos(a)),s=Math.abs(Math.sin(a));return {w:Math.round((item.w*c+item.d*s)*1e10)/1e10,d:Math.round((item.w*s+item.d*c)*1e10)/1e10};}
export function corners(item){const f=footprint(item),cx=item.x+f.w/2,cz=item.z+f.d/2,a=item.rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>({x:cx+x*item.w/2*c-z*item.d/2*s,z:cz+x*item.w/2*s+z*item.d/2*c}));}
function overlaps(a,b,tolerance=.02){for(const poly of [a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],len=Math.hypot(q.x-p.x,q.z-p.z),nx=-(q.z-p.z)/len,nz=(q.x-p.x)/len;const aa=a.map(v=>v.x*nx+v.z*nz),bb=b.map(v=>v.x*nx+v.z*nz);if(Math.max(...aa)<=Math.min(...bb)+tolerance||Math.max(...bb)<=Math.min(...aa)+tolerance)return false;}return true;}
export function placementIssue(state,item,ignoreId=item.id){
 const{w,d}=footprint(item),r=state.room;if(![item.x,item.z,w,d,item.rotation].every(Number.isFinite))return 'Invalid position.';
 if(item.x< -1e-8||item.z< -1e-8||item.x+w>r.width+1e-8||item.z+d>r.depth+1e-8)return 'Keep the whole piece inside the room.';
 const polygon=corners(item);
 if(r.shape==='custom'&&!containsPolygon(roomPolygon(r),polygon))return 'Keep the whole piece inside your traced room.';
 if(r.shape==='l-shape'&&overlaps(polygon,[{x:r.width*.68,z:0},{x:r.width,z:0},{x:r.width,z:r.depth*.3},{x:r.width*.68,z:r.depth*.3}],1e-8))return 'That corner sits outside your L-shaped room.';
 if(item.kind==='rug')return null;
 for(const other of state.items){if(other.id===ignoreId||other.kind==='rug')continue;if(overlaps(polygon,corners(other)))return `That overlaps ${other.name.toLowerCase()}.`;}
 return null;
}
export function moveItem(state,id,x,z){const item=state.items.find(p=>p.id===id);if(!item)return {ok:false,state,reason:'Select a piece first.'};const moved={...item,x:Math.round(x*4)/4,z:Math.round(z*4)/4};const reason=placementIssue(state,moved);return reason?{ok:false,state,reason}:{ok:true,state:{...state,items:state.items.map(p=>p.id===id?moved:p)}};}
export function rotateItem(state,id,degrees=90){const item=state.items.find(p=>p.id===id);if(!item)return{ok:false,state,reason:'Select a piece first.'};const before=footprint(item),next={...item,rotation:((item.rotation+degrees)%360+360)%360},after=footprint(next);next.x+=(before.w-after.w)/2;next.z+=(before.d-after.d)/2;const reason=placementIssue(state,next);return reason?{ok:false,state,reason}:{ok:true,state:{...state,items:state.items.map(p=>p.id===id?next:p)}};}
export function addItem(state,kind){const base=catalog.find(p=>p.kind===kind);if(!base)return{ok:false,state,reason:'That piece is not in this collection.'};if(state.items.length>=35)return{ok:false,state,reason:'This prototype supports 35 pieces per room.'};const item={...base,id:'piece-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),rotation:0};for(let z=.5;z<state.room.depth;z+=.5)for(let x=.5;x<state.room.width;x+=.5){const candidate={...item,x,z};if(!placementIssue(state,candidate))return{ok:true,state:{...state,items:[...state.items,candidate]},id:candidate.id}}return{ok:false,state,reason:'There isn’t an open spot for this piece. Move or remove another item first.'};}
export function validState(s){return Boolean(s?.version===2&&validFinishes(s.finishes)&&s.room&&typeof s.room.name==='string'&&s.room.name.length<=60&&Number.isFinite(s.room.width)&&s.room.width>=4&&s.room.width<=60&&Number.isFinite(s.room.depth)&&s.room.depth>=4&&s.room.depth<=60&&['rectangle','l-shape','custom'].includes(s.room.shape)&&validArchitecture(s)&&Number.isInteger(s.palette)&&s.palette>=0&&s.palette<=2&&Array.isArray(s.items)&&s.items.length<=35&&new Set(s.items.map(p=>p.id)).size===s.items.length&&s.items.every(p=>catalog.some(c=>c.kind===p.kind)&&typeof p.id==='string'&&typeof p.name==='string'&&p.name.length<100&&[p.x,p.z,p.w,p.d,p.h,p.rotation].every(Number.isFinite)&&p.w>0&&p.w<=15&&p.d>0&&p.d<=15&&p.h>0&&p.h<=10&&(p.rotation>=0&&p.rotation<360)&&!placementIssue({...s,items:[]},p)))};
export function serializePlan(state){const r=state.room,scale=Math.min(580/r.width,410/r.depth),ox=(700-r.width*scale)/2,oy=(510-r.depth*scale)/2;const esc=t=>String(t).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));let pieces=state.items.map(p=>{const f=footprint(p);return `<g><rect transform="rotate(${p.rotation} ${ox+(p.x+f.w/2)*scale} ${oy+(p.z+f.d/2)*scale})" x="${ox+(p.x+(f.w-p.w)/2)*scale}" y="${oy+(p.z+(f.d-p.d)/2)*scale}" width="${p.w*scale}" height="${p.d*scale}" rx="${p.kind==='plant'?f.w*scale/2:2}" fill="${catalog.find(c=>c.kind===p.kind).color}" fill-opacity="${p.kind==='rug'?.3:1}" stroke="#765e4d"/><text x="${ox+(p.x+f.w/2)*scale}" y="${oy+(p.z+f.d/2)*scale}" text-anchor="middle" font-size="9" fill="#322a24">${esc(p.name)}</text></g>`}).join('');const path=roomPolygon(r).map((p,i)=>`${i?'L':'M'}${ox+p.x*scale} ${oy+p.z*scale}`).join(' ')+'Z';const attachments=[...(state.openings||[]),...(state.artworks||[])].map(p=>{const w=walls(r)[p.wall],x1=ox+(w.a.x+w.dx*p.offset)*scale,y1=oy+(w.a.z+w.dz*p.offset)*scale,x2=x1+w.dx*p.width*scale,y2=y1+w.dz*p.width*scale;return `<g><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${p.kind==='door'?'#fcf9f1':p.kind==='window'?'#81a7b0':'#833b42'}" stroke-width="7"/><text x="${(x1+x2)/2}" y="${(y1+y2)/2-7}" font-size="8" text-anchor="middle">${p.kind}</text></g>`}).join('');return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 570"><rect width="700" height="570" fill="#f5f1e9"/><path d="${path}" fill="#fcf9f1" stroke="#514336" stroke-width="5"/>${pieces}${attachments}<text x="350" y="535" text-anchor="middle" font-family="sans-serif" font-size="13">${esc(r.name)} · ${+r.width.toFixed(2)} × ${+r.depth.toFixed(2)} ft</text><text x="350" y="556" text-anchor="middle" font-family="sans-serif" font-size="9">IV CORNERS · Concept furniture · Verify measurements and circulation before purchasing</text></svg>`;}
