export const catalog = [
 {kind:'sofa',name:'The linen sofa',category:'Seating',w:7,d:3,h:2.6,color:'#c6b69e',note:'84 × 36 in'},
 {kind:'chair',name:'The reading chair',category:'Seating',w:2.6,d:2.8,h:2.7,color:'#8b7158',note:'31 × 34 in'},
 {kind:'table',name:'The stone table',category:'Tables',w:3.3,d:2,h:1.25,color:'#bba88b',note:'40 × 24 in'},
 {kind:'sideboard',name:'The walnut console',category:'Storage',w:5.4,d:1.4,h:2.5,color:'#72503c',note:'65 × 17 in'},
 {kind:'rug',name:'The woven rug',category:'Finishing touches',w:8,d:6,h:.04,color:'#cbbb9e',note:'8 × 6 ft'},
 {kind:'plant',name:'A little greenery',category:'Finishing touches',w:1.6,d:1.6,h:4.1,color:'#697453',note:'19 × 19 in'},
 {kind:'lamp',name:'The floor lamp',category:'Lighting',w:1.5,d:1.5,h:5,color:'#b09361',note:'18 × 18 in'}
];
export function initialState(){return {version:2,room:{name:'My next chapter',width:16,depth:13,shape:'rectangle'},palette:0,items:[['rug',4.4,5.3],['sofa',5,9.5],['chair',1.2,6.2],['table',7,6.6],['sideboard',5.3,.45],['plant',13.5,1.3]].map(([kind,x,z],i)=>({...catalog.find(p=>p.kind===kind),x,z,id:'piece-'+i,rotation:kind==='sofa'?180:0}))};}
export function footprint(item){return Math.abs(item.rotation%180)===90?{w:item.d,d:item.w}:{w:item.w,d:item.d};}
export function placementIssue(state,item,ignoreId=item.id){
 const{w,d}=footprint(item),r=state.room;if(![item.x,item.z,w,d].every(Number.isFinite))return 'Invalid position.';
 if(item.x<0||item.z<0||item.x+w>r.width||item.z+d>r.depth)return 'Keep the whole piece inside the room.';
 if(r.shape==='l-shape'&&item.x+w>r.width*.68&&item.z<r.depth*.3)return 'That corner sits outside your L-shaped room.';
 if(item.kind==='rug')return null;
 for(const other of state.items){if(other.id===ignoreId||other.kind==='rug')continue;const f=footprint(other);if(item.x<other.x+f.w-.02&&item.x+w>other.x+.02&&item.z<other.z+f.d-.02&&item.z+d>other.z+.02)return `That overlaps ${other.name.toLowerCase()}.`;}
 return null;
}
export function moveItem(state,id,x,z){const item=state.items.find(p=>p.id===id);if(!item)return {ok:false,state,reason:'Select a piece first.'};const moved={...item,x:Math.round(x*4)/4,z:Math.round(z*4)/4};const reason=placementIssue(state,moved);return reason?{ok:false,state,reason}:{ok:true,state:{...state,items:state.items.map(p=>p.id===id?moved:p)}};}
export function rotateItem(state,id){const item=state.items.find(p=>p.id===id);if(!item)return{ok:false,state,reason:'Select a piece first.'};const before=footprint(item),next={...item,rotation:(item.rotation+90)%360},after=footprint(next);next.x+=(before.w-after.w)/2;next.z+=(before.d-after.d)/2;const reason=placementIssue(state,next);return reason?{ok:false,state,reason}:{ok:true,state:{...state,items:state.items.map(p=>p.id===id?next:p)}};}
export function addItem(state,kind){const base=catalog.find(p=>p.kind===kind);if(!base)return{ok:false,state,reason:'That piece is not in this collection.'};if(state.items.length>=35)return{ok:false,state,reason:'This prototype supports 35 pieces per room.'};const item={...base,id:'piece-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),rotation:0};for(let z=.5;z<state.room.depth;z+=.5)for(let x=.5;x<state.room.width;x+=.5){const candidate={...item,x,z};if(!placementIssue(state,candidate))return{ok:true,state:{...state,items:[...state.items,candidate]},id:candidate.id}}return{ok:false,state,reason:'There isn’t an open spot for this piece. Move or remove another item first.'};}
export function validState(s){return Boolean(s?.version===2&&s.room&&typeof s.room.name==='string'&&s.room.name.length<=60&&Number.isFinite(s.room.width)&&s.room.width>=10&&s.room.width<=30&&Number.isFinite(s.room.depth)&&s.room.depth>=10&&s.room.depth<=30&&['rectangle','l-shape'].includes(s.room.shape)&&Number.isInteger(s.palette)&&s.palette>=0&&s.palette<=2&&Array.isArray(s.items)&&s.items.length<=35&&new Set(s.items.map(p=>p.id)).size===s.items.length&&s.items.every(p=>catalog.some(c=>c.kind===p.kind)&&typeof p.id==='string'&&typeof p.name==='string'&&p.name.length<100&&[p.x,p.z,p.w,p.d,p.h,p.rotation].every(Number.isFinite)&&p.w>0&&p.w<=15&&p.d>0&&p.d<=15&&p.h>0&&p.h<=10&&[0,90,180,270].includes(p.rotation)&&!placementIssue({...s,items:[]},p)))};
export function serializePlan(state){const r=state.room,scale=Math.min(580/r.width,410/r.depth),ox=(700-r.width*scale)/2,oy=(510-r.depth*scale)/2;const esc=t=>String(t).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));let pieces=state.items.map(p=>{const f=footprint(p);return `<g><rect x="${ox+p.x*scale}" y="${oy+p.z*scale}" width="${f.w*scale}" height="${f.d*scale}" rx="${p.kind==='plant'?f.w*scale/2:2}" fill="${catalog.find(c=>c.kind===p.kind).color}" fill-opacity="${p.kind==='rug'?.3:1}" stroke="#765e4d"/><text x="${ox+(p.x+f.w/2)*scale}" y="${oy+(p.z+f.d/2)*scale}" text-anchor="middle" font-size="9" fill="#322a24">${esc(p.name)}</text></g>`}).join('');const path=r.shape==='l-shape'?`M${ox} ${oy}h${r.width*.68*scale}v${r.depth*.3*scale}h${r.width*.32*scale}v${r.depth*.7*scale}H${ox}Z`:`M${ox} ${oy}h${r.width*scale}v${r.depth*scale}H${ox}Z`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 570"><rect width="700" height="570" fill="#f5f1e9"/><path d="${path}" fill="#fcf9f1" stroke="#514336" stroke-width="5"/>${pieces}<text x="350" y="535" text-anchor="middle" font-family="sans-serif" font-size="13">${esc(r.name)} · ${r.width} × ${r.depth} ft</text><text x="350" y="556" text-anchor="middle" font-family="sans-serif" font-size="9">IV CORNERS · Concept furniture · Verify measurements and circulation before purchasing</text></svg>`;}
