import * as THREE from 'three';
import { GLTFLoader } from '../vendor/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { footprint, catalog } from './editor-model.js';
export function createRoomScene(container, callbacks){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#eee9df');
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.setClearColor('#eee9df');container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D room view');
 const camera=new THREE.PerspectiveCamera(36,1,.1,150);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=13;controls.maxDistance=65;controls.enablePan=false;controls.touches.ONE=THREE.TOUCH.ROTATE;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;controls.addEventListener('change',render);
 scene.add(new THREE.HemisphereLight(0xfffaf0,0x8c8275,2.4));const sun=new THREE.DirectionalLight(0xfff2d8,3.4);sun.position.set(4,20,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;sun.shadow.normalBias=.035;scene.add(sun);const fill=new THREE.DirectionalLight(0xffffff,.7);fill.position.set(20,8,5);scene.add(fill);
 const structure=new THREE.Group(),furniture=new THREE.Group();scene.add(structure,furniture);let state,selected=null,mode='3d',drag=null,grid,box;
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 const loader=new GLTFLoader(),templates=new Map(),loading=new Set();
 function requestModel(url){if(loading.has(url))return;loading.add(url);loader.load(url,gltf=>{templates.set(url,gltf.scene);if(state)rebuild(state)},undefined,error=>{console.warn('Furniture model unavailable; using concept geometry.',url,error.message)});}
 const materials={};function mat(color){if(!materials[color])materials[color]=new THREE.MeshStandardMaterial({color,roughness:.85,metalness:0});return materials[color]}
 function cuboid(w,h,d,color,x,y,z,parent){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function cylinder(rt,rb,h,color,x,y,z,parent){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,32),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function clear(group){while(group.children.length){const c=group.children.pop();c.traverse(o=>{if(o.geometry&&!o.userData.sharedModel)o.geometry.dispose()});c.parent=null}}
 function model(piece){const group=new THREE.Group(),{w,d,h,kind}=piece;const colors=[['#cbbb9f','#886447','#d0baa0','#b7aa8e'],['#d4d1bf','#7c8068','#cec7b5','#aab09a'],['#9f7470','#623e32','#d4bb91','#a78979']][state.palette];
 if(kind==='sofa'){cuboid(w,.55,d,colors[0],0,.5,0,group);cuboid(w,1.6,.36,colors[0],0,1.6,-d/2+.18,group);for(const x of [-w/2+.2,w/2-.2])cuboid(.4,1.6,d,colors[0],x,1.3,0,group);for(let i=0;i<3;i++){cuboid((w-.9)/3-.04,.27,d-.6,colors[0],-w/2+.45+(i+.5)*(w-.9)/3,.92,.17,group);const pillow=cuboid(.95,1.03,.32,i===0?colors[1]:colors[2],-w/2+1+i*2.15,1.65,-.85,group);pillow.rotation.x=-.12;}for(const x of [-w/2+.3,w/2-.3])for(const z of [-d/2+.3,d/2-.3])cuboid(.12,.35,.12,'#614631',x,.17,z,group)}
 if(kind==='chair'){cuboid(w,.35,d,colors[1],0,.85,0,group);cuboid(w,1.7,.32,colors[1],0,1.6,-d/2+.16,group);cuboid(w-.36,.22,d-.35,colors[0],0,1.13,.15,group);for(const x of [-w/2+.12,w/2-.12]){cuboid(.24,.9,d,colors[1],x,1.48,0,group);for(const z of [-d/2+.2,d/2-.2])cuboid(.14,.7,.14,'#604735',x,.4,z,group)}}
 if(kind==='table'){const top=cylinder(d/2,d/2,.23,colors[2],0,h,0,group);top.scale.x=w/d;cylinder(.65,.72,h-.12,colors[2],0,(h-.12)/2,0,group);cylinder(.19,.19,.35,'#684b36',.4,h+.28,.1,group);cuboid(.7,.06,.5,'#eee7d7',-.5,h+.15,.1,group)}
 if(kind==='sideboard'){cuboid(w,h-.3,d,'#76543e',0,h/2+.15,0,group);cuboid(w+.12,.12,d+.12,'#60442f',0,h+.02,0,group);for(let i=0;i<4;i++){cuboid(.025,h-.5,.02,'#493426',-w/2+(i+1)*w/5,h/2+.15,d/2+.015,group)}cylinder(.28,.35,.8,'#cfbea5',-w*.28,h+.47,0,group);cylinder(.43,.32,.18,'#b1a089',w*.25,h+.17,.03,group)}
 if(kind==='rug'){cuboid(w,.035,d,colors[3],0,.025,0,group);for(let i=1;i<9;i++)cuboid(w-.18,.006,.015,'#d8ccb4',0,.046,-d/2+i*d/9,group)}
 if(kind==='plant'){cylinder(.52,.36,.85,'#b88e71',0,.44,0,group);cylinder(.48,.48,.025,'#574634',0,.88,0,group);cylinder(.045,.065,2.2,'#75644c',0,1.8,0,group);for(let i=0;i<9;i++){const a=i*2.4,r=.35+i%3*.15;const leaf=new THREE.Mesh(new THREE.SphereGeometry(1,12,8),mat(i%2?'#627349':'#798b5e'));leaf.scale.set(.48,.72,.19);leaf.position.set(Math.sin(a)*r,1.6+(i%4)*.55,Math.cos(a)*r);leaf.rotation.set(.3,a,.4);leaf.castShadow=true;group.add(leaf)}}
 if(kind==='lamp'){cylinder(.55,.55,.1,'#665647',0,.08,0,group);cylinder(.035,.035,4.25,'#a98a54',0,2.15,0,group);cylinder(.55,.85,1,'#eee3c8',0,4.45,0,group)}
 const source=catalog.find(p=>p.kind===piece.kind),url=source?.model;
 if(url){if(templates.has(url)){clear(group);const object=templates.get(url).clone(true);const bounds=new THREE.Box3().setFromObject(object),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const wrapper=new THREE.Group();object.position.sub(new THREE.Vector3(center.x,bounds.min.y,center.z));wrapper.add(object);wrapper.scale.set(w/size.x,h/size.y,d/size.z);object.traverse(o=>{o.userData.sharedModel=true;if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});group.add(wrapper);}else{if(!group.children.length)cuboid(w,h,d,piece.color,0,h/2,0,group);requestModel(url);}}
 const f=footprint(piece);group.position.set(piece.x+f.w/2,0,piece.z+f.d/2);group.rotation.y=-THREE.MathUtils.degToRad(piece.rotation);group.userData.id=piece.id;group.traverse(o=>o.userData.id=piece.id);return group;
 }
 function rebuild(next){const roomChanged=!state||state.room.width!==next.room.width||state.room.depth!==next.room.depth||state.room.shape!==next.room.shape;state=next;clear(structure);clear(furniture);const r=state.room;
 const shape=new THREE.Shape();const pts=r.shape==='l-shape'?[[0,0],[r.width*.68,0],[r.width*.68,r.depth*.3],[r.width,r.depth*.3],[r.width,r.depth],[0,r.depth]]:[[0,0],[r.width,0],[r.width,r.depth],[0,r.depth]];pts.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const floor=new THREE.Mesh(new THREE.ShapeGeometry(shape),mat('#d5c4a5'));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;structure.add(floor);
 const base=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.25,bevelEnabled:false}),mat('#d1c6b5'));base.rotation.x=-Math.PI/2;base.position.y=-.27;base.receiveShadow=true;structure.add(base);
 const wallColor=['#e2d9c9','#d7d9cc','#d5c4b6'][state.palette];cuboid(r.width*(r.shape==='l-shape'?.68:1),6.6,.18,wallColor,r.width*(r.shape==='l-shape'?.68:1)/2,3.3,-.08,structure);cuboid(.18,6.6,r.depth,wallColor,-.08,3.3,r.depth/2,structure);
 // The window and art are illustrative architectural details, not inferred measurements.
 cuboid(.04,4,5,'#bba88e',.04,4,r.depth*.42,structure);cuboid(.05,3.7,4.7,'#eaf0e9',.07,4,r.depth*.42,structure);cuboid(.06,.07,4.7,'#bba88e',.11,4,r.depth*.42,structure);cuboid(.06,3.7,.07,'#bba88e',.11,4,r.depth*.42,structure);
 cuboid(2.2,2.9,.1,'#76543c',r.width*.4,4.6,.12,structure);cuboid(2,2.7,.1,'#eee3cc',r.width*.4,4.6,.2,structure);cuboid(1.1,1.8,.02,'#935548',r.width*.4-.15,4.5,.26,structure);cylinder(.42,.42,.025,'#ceb17f',0,0,0,new THREE.Group());
 // Subtle plank joints on the room floor.
 for(let x=1;x<r.width;x+=1){const start=r.shape==='l-shape'&&x>r.width*.68?r.depth*.3:0;cuboid(.012,.006,r.depth-start,'#c4b291',x,.008,(start+r.depth)/2,structure)}
 state.items.forEach(p=>furniture.add(model(p)));if(roomChanged)resetCamera();else if(mode==='2d')structure.children.forEach(m=>{m.visible=m.position.y<1});setSelected(selected);render();}
 function render(){renderer.render(scene,camera)}
 function resetCamera(){if(!state)return;const{width:w,depth:d}=state.room;controls.target.set(w/2,0,d/2);if(mode==='2d'){camera.position.set(w/2,Math.max(w,d)*1.7,d/2+.001);controls.enableRotate=false;structure.children.forEach(m=>{m.visible=m.position.y<1})}else{const fit=Math.max(1,1/camera.aspect);camera.position.set(w/2+w*.95*fit,Math.max(w,d)*1.45*fit,d/2+d*1.3*fit);controls.enableRotate=true;structure.children.forEach(m=>m.visible=true)}camera.lookAt(controls.target);controls.update();render()}
 function setMode(next){mode=next;resetCamera()}
 function setSelected(id){selected=id;if(box){scene.remove(box);box.geometry.dispose();box.material.dispose();box=null}const g=furniture.children.find(g=>g.userData.id===id);if(g){box=new THREE.BoxHelper(g,0x8a3940);box.material.depthTest=false;box.renderOrder=10;scene.add(box)}render()}
 function worldPoint(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(floorPlane,new THREE.Vector3())}
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;worldPoint(e);const hit=raycaster.intersectObjects(furniture.children,true).find(h=>h.object.userData.id);if(!hit)return;const id=hit.object.userData.id,item=state.items.find(x=>x.id===id),point=worldPoint(e);if(!point)return;controls.enabled=false;drag={id,startX:e.clientX,startY:e.clientY,dx:point.x-item.x,dz:point.z-item.z,x:item.x,z:item.z};callbacks.select(id);renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation()},true);
 renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const p=worldPoint(e);if(!p)return;drag.x=p.x-drag.dx;drag.z=p.z-drag.dz;const g=furniture.children.find(x=>x.userData.id===drag.id),item=state.items.find(x=>x.id===drag.id),f=footprint(item);if(g){g.position.x=drag.x+f.w/2;g.position.z=drag.z+f.d/2;box?.update();render()}},true);
 function endDrag(e){if(!drag)return;const d=drag;drag=null;controls.enabled=true;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);if(e.type==='pointercancel'){rebuild(state);return}callbacks.move(d.id,d.x,d.z)}
 renderer.domElement.addEventListener('pointerup',endDrag,true);renderer.domElement.addEventListener('pointercancel',endDrag,true);
 renderer.domElement.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'});renderer.domElement.addEventListener('drop',e=>{e.preventDefault();const kind=e.dataTransfer.getData('text/iv-furniture'),p=worldPoint(e);if(kind&&p)callbacks.drop(kind,p.x,p.z)});
 const resizeObserver=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);if(state)resetCamera();render()});resizeObserver.observe(container);
 return {update:rebuild,select:setSelected,setMode,resetCamera,render,canvas:renderer.domElement,projectItem(id){const p=state.items.find(x=>x.id===id),f=footprint(p),v=new THREE.Vector3(p.x+f.w/2,.8,p.z+f.d/2).project(camera),rect=renderer.domElement.getBoundingClientRect();return{x:rect.left+(v.x+1)/2*rect.width,y:rect.top+(-v.y+1)/2*rect.height}}};
}
