import {assistedPlacement,measureGaps} from './design-tools-model.js';
import {floorMaterial} from './room-finishes.js';
import {finishesFor} from './finishes.js';
import {roomPolygon,pointInside,containsPolygon} from './space-model.js';
import {buildWalls,updateWallVisibility} from './room-architecture.js';
import * as THREE from 'three';
import { GLTFLoader } from '../vendor/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { footprint, catalog } from './editor-model.js';
export function createRoomScene(container, callbacks){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#eee9df');
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.setClearColor('#eee9df');container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D room view');
 const camera=new THREE.PerspectiveCamera(36,1,.1,500);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=13;controls.maxDistance=250;controls.enablePan=false;controls.touches.ONE=THREE.TOUCH.ROTATE;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;controls.addEventListener('change',render);
 const sky=new THREE.HemisphereLight(0xfffaf0,0x8c8275,2.4);scene.add(sky);const sun=new THREE.DirectionalLight(0xfff2d8,3.4);sun.position.set(4,20,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;sun.shadow.normalBias=.035;scene.add(sun);const fill=new THREE.DirectionalLight(0xffffff,.7);fill.position.set(20,8,5);scene.add(fill);
 const structure=new THREE.Group(),furniture=new THREE.Group(),guides=new THREE.Group();scene.add(structure,furniture,guides);const guideOverlay=document.createElement('div');guideOverlay.className='guide-overlay';guideOverlay.setAttribute('aria-hidden','true');container.append(guideOverlay);let guideLabels=[];let state,selected=null,mode='3d',drag=null,lookDrag=null,yaw=Math.PI,pitch=0,grid,box;
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 const loader=new GLTFLoader(),templates=new Map(),loading=new Set(),pending=new Set(),failed=new Set();
 function requestModel(url){if(loading.has(url))return;loading.add(url);pending.add(url);loader.load(url,gltf=>{pending.delete(url);templates.set(url,gltf.scene);if(state)rebuild(state)},undefined,error=>{pending.delete(url);failed.add(url);console.warn('Furniture model unavailable; using concept geometry.',url,error.message)});}
 const materials={};function mat(color){if(!materials[color])materials[color]=new THREE.MeshStandardMaterial({color,roughness:.85,metalness:0});return materials[color]}
 function cuboid(w,h,d,color,x,y,z,parent){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function cylinder(rt,rb,h,color,x,y,z,parent){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,32),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function clear(group){while(group.children.length){const c=group.children.pop();c.traverse(o=>{if(o.geometry&&!o.userData.sharedModel)o.geometry.dispose();if(o.userData.disposeMaterial)o.material.dispose()});c.parent=null}}
 function model(piece){const group=new THREE.Group(),{w,d,h,kind}=piece;const colors=[['#cbbb9f','#886447','#d0baa0','#b7aa8e'],['#d4d1bf','#7c8068','#cec7b5','#aab09a'],['#9f7470','#623e32','#d4bb91','#a78979']][state.palette];
 if(kind==='sofa'){cuboid(w,.55,d,colors[0],0,.5,0,group);cuboid(w,1.6,.36,colors[0],0,1.6,-d/2+.18,group);for(const x of [-w/2+.2,w/2-.2])cuboid(.4,1.6,d,colors[0],x,1.3,0,group);for(let i=0;i<3;i++){cuboid((w-.9)/3-.04,.27,d-.6,colors[0],-w/2+.45+(i+.5)*(w-.9)/3,.92,.17,group);const pillow=cuboid(.95,1.03,.32,i===0?colors[1]:colors[2],-w/2+1+i*2.15,1.65,-.85,group);pillow.rotation.x=-.12;}for(const x of [-w/2+.3,w/2-.3])for(const z of [-d/2+.3,d/2-.3])cuboid(.12,.35,.12,'#614631',x,.17,z,group)}
 if(kind==='chair'){cuboid(w,.35,d,colors[1],0,.85,0,group);cuboid(w,1.7,.32,colors[1],0,1.6,-d/2+.16,group);cuboid(w-.36,.22,d-.35,colors[0],0,1.13,.15,group);for(const x of [-w/2+.12,w/2-.12]){cuboid(.24,.9,d,colors[1],x,1.48,0,group);for(const z of [-d/2+.2,d/2-.2])cuboid(.14,.7,.14,'#604735',x,.4,z,group)}}
 if(kind==='table'){const top=cylinder(d/2,d/2,.23,colors[2],0,h,0,group);top.scale.x=w/d;cylinder(.65,.72,h-.12,colors[2],0,(h-.12)/2,0,group);cylinder(.19,.19,.35,'#684b36',.4,h+.28,.1,group);cuboid(.7,.06,.5,'#eee7d7',-.5,h+.15,.1,group)}
 if(kind==='sideboard'){cuboid(w,h-.3,d,'#76543e',0,h/2+.15,0,group);cuboid(w+.12,.12,d+.12,'#60442f',0,h+.02,0,group);for(let i=0;i<4;i++){cuboid(.025,h-.5,.02,'#493426',-w/2+(i+1)*w/5,h/2+.15,d/2+.015,group)}cylinder(.28,.35,.8,'#cfbea5',-w*.28,h+.47,0,group);cylinder(.43,.32,.18,'#b1a089',w*.25,h+.17,.03,group)}
 if(kind==='rug'){cuboid(w,.035,d,colors[3],0,.025,0,group);for(let i=1;i<9;i++)cuboid(w-.18,.006,.015,'#d8ccb4',0,.046,-d/2+i*d/9,group)}
 if(kind==='plant'){cylinder(.52,.36,.85,'#b88e71',0,.44,0,group);cylinder(.48,.48,.025,'#574634',0,.88,0,group);cylinder(.045,.065,2.2,'#75644c',0,1.8,0,group);for(let i=0;i<9;i++){const a=i*2.4,r=.35+i%3*.15;const leaf=new THREE.Mesh(new THREE.SphereGeometry(1,12,8),mat(i%2?'#627349':'#798b5e'));leaf.scale.set(.48,.72,.19);leaf.position.set(Math.sin(a)*r,1.6+(i%4)*.55,Math.cos(a)*r);leaf.rotation.set(.3,a,.4);leaf.castShadow=true;group.add(leaf)}}
 if(kind==='lamp'){cylinder(.55,.55,.1,'#665647',0,.08,0,group);cylinder(.035,.035,4.25,'#a98a54',0,2.15,0,group);cylinder(.55,.85,1,'#eee3c8',0,4.45,0,group)}
 const source=catalog.find(p=>p.kind===piece.kind),url=source?.model;
 if(url){if(templates.has(url)){clear(group);const object=templates.get(url).clone(true);const bounds=new THREE.Box3().setFromObject(object),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const wrapper=new THREE.Group();object.position.sub(new THREE.Vector3(center.x,bounds.min.y,center.z));wrapper.add(object);wrapper.scale.set(w/size.x,h/size.y,d/size.z);object.traverse(o=>{o.userData.sharedModel=true;if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});group.add(wrapper);}else{if(!group.children.length)cuboid(w,h,d,piece.color,0,h/2,0,group);requestModel(url);}}
 const f=footprint(piece);group.position.set(piece.x+f.w/2,0,piece.z+f.d/2);group.rotation.y=-THREE.MathUtils.degToRad(piece.rotation);group.userData.id=piece.id;group.traverse(o=>o.userData.id=piece.id);return group;
 }
 function rebuild(next){const roomChanged=!state||state.room.width!==next.room.width||state.room.depth!==next.room.depth||JSON.stringify(state.room.vertices)!==JSON.stringify(next.room.vertices)||state.room.shape!==next.room.shape;state=next;const evening=finishesFor(state).light==='evening';sun.color.set(evening?'#ffbd78':'#fff2d8');sun.intensity=evening?2.2:3.4;sky.intensity=evening?1.5:2.4;renderer.toneMappingExposure=evening?.9:1;clear(structure);clear(furniture);const r=state.room;
 const shape=new THREE.Shape();const pts=roomPolygon(r).map(p=>[p.x,p.z]);pts.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const floor=new THREE.Mesh(new THREE.ShapeGeometry(shape),floorMaterial(state,mat));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;structure.add(floor);
 const base=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.25,bevelEnabled:false}),mat('#d1c6b5'));base.rotation.x=-Math.PI/2;base.position.y=-.27;base.receiveShadow=true;structure.add(base);
 buildWalls(state,structure,cuboid,mat,render);
 state.items.forEach(p=>furniture.add(model(p)));if(roomChanged)resetCamera();setSelected(selected);render();}
 function render(){updateWallVisibility(structure,mode,camera);guides.visible=mode!=='eye';guideOverlay.hidden=mode==='eye';renderer.render(scene,camera);for(const {el,point} of guideLabels){const p=point.clone().project(camera);el.hidden=p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;el.style.left=`${(p.x+1)/2*container.clientWidth}px`;el.style.top=`${(-p.y+1)/2*container.clientHeight}px`;}}
 function resetCamera(){if(!state)return;const{width:w,depth:d}=state.room;camera.fov=mode==='eye'?65:36;camera.updateProjectionMatrix();controls.enabled=mode!=='eye';controls.target.set(w/2,mode==='3d'?1.3:0,d/2);
 if(mode==='eye'){let position={x:w/2,z:d*.8};if(!pointInside(position,roomPolygon(state.room))){outer:for(let z=d-.6;z>.4;z-=.5)for(let x=.6;x<w;x+=.5){if(pointInside({x,z},roomPolygon(state.room))){position={x,z};break outer;}}}camera.position.set(position.x,5.3,position.z);yaw=Math.PI;pitch=0;look();return;}
 if(mode==='2d'){camera.position.set(w/2,Math.max(w,d)*1.7,d/2+.001);controls.enableRotate=false}else{const fit=Math.max(1,1/camera.aspect);camera.position.set(w/2+w*1.05*fit,Math.max(w,d)*1.6*fit,d/2+d*1.43*fit);controls.enableRotate=true}camera.lookAt(controls.target);controls.update();render();}
 function look(){camera.lookAt(camera.position.x+Math.sin(yaw)*Math.cos(pitch),camera.position.y+Math.sin(pitch),camera.position.z+Math.cos(yaw)*Math.cos(pitch));render();}
 function walk(action){if(mode!=='eye')return;if(action==='turn-left'||action==='turn-right'){yaw+=action==='turn-left'?.15:-.15;look();return;}const direction=action==='back'?-1:1,side=action==='left'||action==='right',angle=yaw+(side?(action==='left'?Math.PI/2:-Math.PI/2):0);const target={x:camera.position.x+Math.sin(angle)*.5*direction,z:camera.position.z+Math.cos(angle)*.5*direction};const poly=roomPolygon(state.room);const safe=containsPolygon(poly,[{x:camera.position.x,z:camera.position.z},target])&&[target,{x:target.x+.15,z:target.z},{x:target.x-.15,z:target.z},{x:target.x,z:target.z+.15},{x:target.x,z:target.z-.15}].every(p=>pointInside(p,poly));if(safe){camera.position.x=target.x;camera.position.z=target.z;look();}}
 function setMode(next){mode=next;resetCamera();if(box)box.visible=mode!=='eye'}
 function setSelected(id){selected=id;if(box){scene.remove(box);box.geometry.dispose();box.material.dispose();box=null}const g=furniture.children.find(g=>g.userData.id===id);if(g){box=new THREE.BoxHelper(g,0x8a3940);box.material.depthTest=false;box.renderOrder=10;scene.add(box);box.visible=mode!=='eye'}showGuides(state,id);render()}
 function showGuides(current,id,alignment=[]){clear(guides);guideOverlay.replaceChildren();guideLabels=[];if(!id||callbacks.guidesEnabled?.()===false)return;const measurements=measureGaps(current,id);for(const g of [...measurements,...alignment]){const color=g.kind==='piece'?0x556e74:g.kind==='wall'?0x756244:0x8b3041;const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(g.a.x,.1,g.a.z),new THREE.Vector3(g.b.x,.1,g.b.z)]);const line=new THREE.Line(geometry,new THREE.LineDashedMaterial({color,dashSize:.14,gapSize:.09,depthTest:false}));line.computeLineDistances();line.renderOrder=20;line.userData.disposeMaterial=true;guides.add(line);if(g.distance!==undefined){const el=document.createElement('span');el.textContent=`${(g.distance*12).toFixed(0)}″`;guideOverlay.append(el);guideLabels.push({el,point:new THREE.Vector3((g.a.x+g.b.x)/2,.2,(g.a.z+g.b.z)/2)});}}}
 async function ready(){for(let i=0;i<100;i++){let texturesPending=false;scene.traverse(o=>{const m=o.material;if(m?.map&&!m.map.image?.width)texturesPending=true});if(!pending.size&&!texturesPending){if(failed.size)throw Error('A furniture model failed to load. Reload before exporting this view.');return;}await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Models are still loading. Try again in a moment.');}
 function capture(){const visible=box?.visible;if(box)box.visible=false;guides.visible=false;updateWallVisibility(structure,mode,camera);renderer.render(scene,camera);try{return renderer.domElement.toDataURL('image/png')}finally{if(box)box.visible=visible;render();}}
 function getCamera(){return {mode,position:camera.position.toArray(),target:controls.target.toArray(),yaw,pitch};}
 function restoreCamera(saved){if(!saved||!['3d','2d','eye'].includes(saved.mode)||![saved.position,saved.target].every(a=>Array.isArray(a)&&a.length===3&&a.every(v=>Number.isFinite(v)&&Math.abs(v)<500)))return;mode=saved.mode;resetCamera();camera.position.fromArray(saved.position);controls.target.fromArray(saved.target);if(mode==='eye'){yaw=Number.isFinite(saved.yaw)?saved.yaw:Math.PI;pitch=Number.isFinite(saved.pitch)?saved.pitch:0;look();}else{camera.lookAt(controls.target);controls.update();render();}}
 function worldPoint(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(floorPlane,new THREE.Vector3())}
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(mode==='eye'){lookDrag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation();return}worldPoint(e);const hit=raycaster.intersectObjects(furniture.children,true).find(h=>h.object.userData.id);if(!hit)return;const id=hit.object.userData.id,item=state.items.find(x=>x.id===id),point=worldPoint(e);if(!point)return;controls.enabled=false;drag={id,startX:e.clientX,startY:e.clientY,dx:point.x-item.x,dz:point.z-item.z,x:item.x,z:item.z};callbacks.select(id);renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation()},true);
 renderer.domElement.addEventListener('pointermove',e=>{if(lookDrag){yaw-=(e.clientX-lookDrag.x)*.005;pitch=Math.max(-1.1,Math.min(1.1,pitch+(e.clientY-lookDrag.y)*.005));lookDrag={x:e.clientX,y:e.clientY};look();return}if(!drag)return;const p=worldPoint(e);if(!p)return;drag.x=p.x-drag.dx;drag.z=p.z-drag.dz;const g=furniture.children.find(x=>x.userData.id===drag.id),item=state.items.find(x=>x.id===drag.id),f=footprint(item);if(g){const assisted=assistedPlacement(state,drag.id,drag.x,drag.z,callbacks.guidesEnabled?.()!==false),preview=assisted.ok?assisted.item:{...item,x:drag.x,z:drag.z};g.position.x=preview.x+f.w/2;g.position.z=preview.z+f.d/2;if(box)box.material.color.set(assisted.ok?0x8a3940:0xc13529);showGuides(assisted.ok?assisted.state:state,drag.id,assisted.lines||[]);callbacks.placementHint?.(assisted.ok?assisted.label:assisted.reason);box?.update();render()}},true);
 function endDrag(e){if(lookDrag){lookDrag=null;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);return}if(!drag)return;const d=drag;drag=null;controls.enabled=true;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);if(e.type==='pointercancel'){rebuild(state);return}callbacks.move(d.id,d.x,d.z)}
 renderer.domElement.addEventListener('pointerup',endDrag,true);renderer.domElement.addEventListener('pointercancel',endDrag,true);
 renderer.domElement.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'});renderer.domElement.addEventListener('drop',e=>{e.preventDefault();const kind=e.dataTransfer.getData('text/iv-furniture'),p=worldPoint(e);if(kind&&p)callbacks.drop(kind,p.x,p.z)});
 const resizeObserver=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);if(state)resetCamera();render()});resizeObserver.observe(container);
 return {update:rebuild,select:setSelected,setMode,resetCamera,walk,render,ready,capture,getCamera,restoreCamera,refreshGuides(){showGuides(state,selected);render()},canvas:renderer.domElement,projectItem(id){const p=state.items.find(x=>x.id===id),f=footprint(p),v=new THREE.Vector3(p.x+f.w/2,.8,p.z+f.d/2).project(camera),rect=renderer.domElement.getBoundingClientRect();return{x:rect.left+(v.x+1)/2*rect.width,y:rect.top+(-v.y+1)/2*rect.height}}};
}
