import {calibrateTrace,roomPolygon,walls,attachmentIssue} from './space-model.js';
import {placementIssue} from './editor-model.js';
const $=s=>document.querySelector(s);
export async function localImage(file,maxSide=1200){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)throw Error('Choose a JPG, PNG, or WebP image under 12 MB.');const url=URL.createObjectURL(file),image=new Image();try{image.src=url;await image.decode();const scale=Math.min(1,maxSide/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return {data:canvas.toDataURL('image/jpeg',.8),width:canvas.width,height:canvas.height};}finally{URL.revokeObjectURL(url);}}
export function setupSpaceTools({getState,commit,toast}){
 document.body.insertAdjacentHTML('beforeend',`
 <dialog id="trace-dialog" class="space-dialog" aria-labelledby="trace-title"><header><div><p class="eyebrow">YOUR HOME, TO SCALE</p><h2 id="trace-title">Start with your <em>floor plan.</em></h2></div><button data-space-close aria-label="Close floor-plan tracing">×</button></header>
 <div class="trace-layout"><div class="trace-board"><svg id="trace-canvas" viewBox="0 0 1000 700" aria-label="Floor-plan tracing surface" role="img"></svg><div id="trace-empty">A plan from your listing.<br>A sketch on paper.<br><em>Your starting point.</em></div></div><section class="trace-instructions">
 <label class="upload-plan" for="plan-file">01 &nbsp; Upload a floor-plan image ↗<input id="plan-file" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="space-note">JPG, PNG or WebP. For a PDF, export one page as an image first. The guide stays in this tab; your traced room is saved with the project.</p>
 <p id="trace-step" class="trace-step" role="status">Upload a plan to begin.</p>
 <label for="known-feet">02 &nbsp; Known distance (feet)<input id="known-feet" type="number" min=".1" max="100" step=".1" value="10"></label>
 <div class="space-button-row"><button id="trace-calibrate" disabled>Set scale & trace ↗</button><button id="trace-rescale" disabled>Reset scale</button></div>
 <p class="space-note">Mark the two ends of a dimension you know. Then trace the inside corners around one room in order. Finish with “Build my room.”</p>
 <details class="trace-coordinates"><summary>Place a point by coordinates</summary><div class="dimension-fields"><label>X (image px)<input id="trace-x" type="number" min="0" value="0"></label><label>Y (image px)<input id="trace-y" type="number" min="0" value="0"></label></div><button id="trace-add-point">Add point</button></details>
 <div class="space-button-row"><button id="trace-undo">Undo point</button><button id="trace-clear">Clear outline</button></div><p id="trace-result" role="status"></p>
 <p class="space-note">This replaces the room outline and clears existing wall attachments. Furniture that fits is kept. Undo restores the previous room.</p><button id="trace-build" class="solid-button" disabled>Build my room ↗</button></section></div></dialog>
 <dialog id="walls-dialog" class="space-dialog" aria-labelledby="walls-title"><header><div><p class="eyebrow">THE DETAILS THAT MAKE IT YOURS</p><h2 id="walls-title">Openings & <em>art.</em></h2></div><button data-space-close aria-label="Close walls and art">×</button></header><div class="walls-layout"><section><svg id="wall-map" viewBox="0 0 500 400" aria-label="Numbered room walls"></svg><p class="space-note">Choose a numbered wall. Distances start at its first corner, following the arrow. Openings and art appear in all room views.</p><div id="wall-attachments" class="wall-attachments"></div><button id="new-attachment" class="text-button">＋ Add another detail</button></section><form id="attachment-form">
 <div class="dimension-fields"><label for="attachment-kind">What are we adding?<select id="attachment-kind"><option value="door">Door opening</option><option value="window">Window</option><option value="art">Your artwork</option></select></label><label for="attachment-wall">Wall<select id="attachment-wall"></select></label></div>
 <label id="art-upload-label" for="art-file" hidden>Upload your artwork<input id="art-file" type="file" accept="image/jpeg,image/png,image/webp"><img id="art-preview" alt="Your artwork preview" hidden></label>
 <div class="dimension-fields"><label for="attachment-width">Width (inches)<input id="attachment-width" type="number" min="3" max="360" step="1" value="36" required></label><label for="attachment-height">Height (inches)<input id="attachment-height" type="number" min="3" max="180" step="1" value="80" required></label></div>
 <label for="attachment-offset">Distance from wall start (feet)<input id="attachment-offset" type="number" min="0" max="60" step=".1" value="1" required></label><label for="attachment-bottom">Bottom edge above floor (feet)<input id="attachment-bottom" type="number" min="0" max="14" step=".1" value="0" required></label>
 <p class="space-note" id="attachment-tip">An open doorway. Door swing and circulation are not checked.</p><p id="attachment-error" class="space-error" role="alert"></p><div class="space-button-row"><button class="solid-button" type="submit">Add to my wall ↗</button><button id="delete-attachment" type="button" hidden>Remove</button></div><p class="space-note">Artwork is resized locally and included when you save this room on your device. Nothing is uploaded to a server.</p></form></div></dialog>`);
 document.querySelectorAll('[data-space-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 let guide=null,reference=[],points=[],phase='reference';
 function drawTrace(){const svg=$('#trace-canvas');svg.replaceChildren();if(!guide)return;svg.setAttribute('viewBox',`0 0 ${guide.width} ${guide.height}`);$('#trace-empty').hidden=true;const NS='http://www.w3.org/2000/svg';const el=(type,attrs,text)=>{const n=document.createElementNS(NS,type);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.append(n);return n};el('image',{href:guide.data,width:guide.width,height:guide.height,opacity:.72});const radius=Math.max(guide.width,guide.height)/100;
 if(reference.length)el('polyline',{points:reference.map(p=>`${p.x},${p.z}`).join(' '),stroke:'#286c80','stroke-width':radius/3,fill:'none'});
 if(points.length)el('polygon',{points:points.map(p=>`${p.x},${p.z}`).join(' '),stroke:'#782c38','stroke-width':radius/3,fill:'#782c38','fill-opacity':.12});
 for(const [list,color] of [[reference,'#286c80'],[points,'#782c38']])list.forEach((p,i)=>{el('circle',{cx:p.x,cy:p.z,r:radius,fill:color});el('text',{x:p.x,y:p.z+radius*.35,fill:'white','text-anchor':'middle','font-size':radius*1.25},String(i+1))});
 $('#trace-step').textContent=phase==='reference'?`Mark two ends of a known measurement (${reference.length}/2).`:`03  Trace room corners in order · ${points.length} points`;
 $('#trace-calibrate').disabled=reference.length!==2||phase==='outline';$('#trace-rescale').disabled=false;$('#trace-build').disabled=phase!=='outline'||points.length<3;
 $('#trace-result').textContent='';if(points.length>=3)try{const r=calibrateTrace(points,reference,+$('#known-feet').value);$('#trace-result').textContent=`${r.width.toFixed(1)}′ × ${r.depth.toFixed(1)}′ · ${points.length} walls`;}catch(error){$('#trace-result').textContent=error.message;$('#trace-build').disabled=true;}
 }
 function addPoint(p){if(!guide)return;if(p.x<0||p.z<0||p.x>guide.width||p.z>guide.height){toast('Place the point inside the image.');return}if(phase==='reference'){if(reference.length===2)reference=[];reference.push(p)}else{if(points.length>=24){toast('Use up to 24 corners.');return}points.push(p)}drawTrace();}
 $('#trace-canvas').addEventListener('click',e=>{if(!guide)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(e.currentTarget.getScreenCTM().inverse());addPoint({x:p.x,z:p.y});});
 $('#trace-add-point').onclick=()=>addPoint({x:+$('#trace-x').value,z:+$('#trace-y').value});
 $('#plan-file').onchange=async e=>{try{guide=await localImage(e.target.files[0]);reference=[];points=[];phase='reference';drawTrace()}catch(error){toast(error.message)}e.target.value=''};
 $('#trace-calibrate').onclick=()=>{const feet=+$('#known-feet').value;if(reference.length!==2||feet<=0||feet>100||Math.hypot(reference[1].x-reference[0].x,reference[1].z-reference[0].z)<5){$('#trace-result').textContent='Choose two distinct points and a valid known distance.';return}phase='outline';drawTrace();};
 $('#trace-rescale').onclick=()=>{phase='reference';reference=[];points=[];drawTrace()};$('#trace-undo').onclick=()=>{(phase==='reference'?reference:points).pop();drawTrace()};$('#trace-clear').onclick=()=>{points=[];drawTrace()};$('#known-feet').oninput=drawTrace;
 $('#trace-build').onclick=()=>{try{const room=calibrateTrace(points,reference,+$('#known-feet').value),state=getState(),next={...state,room:{...room,name:state.room.name,height:state.room.height||8},openings:[],artworks:[]};next.items=state.items.filter(p=>!placementIssue({...next,items:[]},p));commit(next);$('#trace-dialog').close();toast(`Room traced. ${state.items.length-next.items.length} pieces returned to the collection. Undo is available.`)}catch(error){$('#trace-result').textContent=error.message;}};
 let editId=null,artImage=null,artAspect=1;
 function drawWallMap(){const state=getState(),r=state.room,ws=walls(r),svg=$('#wall-map'),scale=Math.min(400/r.width,300/r.depth),ox=(500-r.width*scale)/2,oy=(400-r.depth*scale)/2;svg.innerHTML='';const NS='http://www.w3.org/2000/svg';for(const w of ws){const line=document.createElementNS(NS,'line');for(const [k,v] of Object.entries({x1:ox+w.a.x*scale,y1:oy+w.a.z*scale,x2:ox+w.b.x*scale,y2:oy+w.b.z*scale,stroke:w.index===+$('#attachment-wall').value?'#782c38':'#b9ae9c','stroke-width':7}))line.setAttribute(k,v);line.style.cursor='pointer';line.onclick=()=>{$('#attachment-wall').value=w.index;drawWallMap()};svg.append(line);const t=document.createElementNS(NS,'text');t.setAttribute('x',ox+(w.a.x+w.dx*w.length*.45-w.dz*.7)*scale);t.setAttribute('y',oy+(w.a.z+w.dz*w.length*.45+w.dx*.7)*scale);t.setAttribute('text-anchor','middle');t.setAttribute('font-size',14);t.textContent=`${w.index+1} ${Math.abs(w.dx)>Math.abs(w.dz)?(w.dx>0?'→':'←'):(w.dz>0?'↓':'↑')}`;svg.append(t);}}
 function refreshWalls(){const state=getState(),selected=$('#attachment-wall').value;$('#attachment-wall').replaceChildren();walls(state.room).forEach(w=>{const o=new Option(`Wall ${w.index+1} · ${w.length.toFixed(1)} ft`,w.index);$('#attachment-wall').add(o)});if([...$('#attachment-wall').options].some(o=>o.value===selected))$('#attachment-wall').value=selected;
 $('#wall-attachments').replaceChildren();for(const p of [...(state.openings||[]),...(state.artworks||[])]){const b=document.createElement('button');b.textContent=`${p.kind==='art'?'Artwork':p.kind==='door'?'Door':'Window'} · wall ${p.wall+1} · ${Math.round(p.width*12)} × ${Math.round(p.height*12)} in`;b.onclick=()=>{editId=p.id;artImage=p.image||null;artAspect=p.imageAspect||p.width/p.height;$('#attachment-kind').value=p.kind;$('#attachment-wall').value=p.wall;$('#attachment-width').value=Math.round(p.width*12);$('#attachment-height').value=Math.round(p.height*12);$('#attachment-offset').value=p.offset;$('#attachment-bottom').value=p.bottom;$('#delete-attachment').hidden=false;$('#attachment-form button[type=submit]').textContent='Update my wall ↗';syncKind(false);drawWallMap()};$('#wall-attachments').append(b);}drawWallMap();}
 function syncKind(reset=true){const kind=$('#attachment-kind').value;$('#art-upload-label').hidden=kind!=='art';$('#attachment-bottom').disabled=kind==='door';if(reset){$('#attachment-width').value=kind==='art'?24:kind==='window'?48:36;$('#attachment-height').value=kind==='art'?30:kind==='window'?48:80;$('#attachment-bottom').value=kind==='door'?0:kind==='art'?3:2.5;}$('#art-preview').hidden=!artImage;if(artImage)$('#art-preview').src=artImage;$('#attachment-tip').textContent=kind==='door'?'An open doorway. Door swing and circulation are not checked.':kind==='art'?'Set the real artwork dimensions; its image is fitted without cropping.':'Window dimensions include the opening. Adjust the sill height above the floor.';$('#attachment-error').textContent='';}
 function resetAttachment(){editId=null;artImage=null;$('#delete-attachment').hidden=true;$('#attachment-form button[type=submit]').textContent='Add to my wall ↗';syncKind();}
 $('#attachment-kind').onchange=()=>syncKind();$('#attachment-wall').onchange=drawWallMap;$('#new-attachment').onclick=resetAttachment;
 $('#art-file').onchange=async e=>{try{const image=await localImage(e.target.files[0],768);if(image.data.length>=700000)throw Error('Choose a simpler or smaller artwork image.');artImage=image.data;artAspect=image.width/image.height;$('#attachment-height').value=Math.round(+$('#attachment-width').value*image.height/image.width);syncKind(false)}catch(error){$('#attachment-error').textContent=error.message}e.target.value=''};
 $('#attachment-form').onsubmit=e=>{e.preventDefault();const s=getState(),kind=$('#attachment-kind').value,p={id:editId||'wall-'+crypto.randomUUID(),kind,wall:+$('#attachment-wall').value,offset:+$('#attachment-offset').value,width:+$('#attachment-width').value/12,height:+$('#attachment-height').value/12,bottom:kind==='door'?0:+$('#attachment-bottom').value};if(kind==='art'){if(!artImage){$('#attachment-error').textContent='Choose an artwork image first.';return}p.image=artImage;p.imageAspect=artAspect;}const all=[...(s.openings||[]),...(s.artworks||[])];if(!editId&&all.length>=24){$('#attachment-error').textContent='This room supports 24 wall details.';return}const issue=attachmentIssue(s.room,p,all);if(issue){$('#attachment-error').textContent=issue;return}const next={...s,openings:(s.openings||[]).filter(x=>x.id!==p.id),artworks:(s.artworks||[]).filter(x=>x.id!==p.id)};next[kind==='art'?'artworks':'openings'].push(p);if(JSON.stringify(next).length>3500000){$('#attachment-error').textContent='This room has reached its local image budget. Remove an artwork first.';return}commit(next);toast(editId?'Wall detail updated.':'Added to your wall.');resetAttachment();refreshWalls();};
 $('#delete-attachment').onclick=()=>{if(!editId)return;const s=getState();commit({...s,openings:(s.openings||[]).filter(p=>p.id!==editId),artworks:(s.artworks||[]).filter(p=>p.id!==editId)});resetAttachment();refreshWalls()};
 return {trace(){drawTrace();$('#trace-dialog').showModal()},walls(){resetAttachment();refreshWalls();$('#walls-dialog').showModal()}};
}
