const EPS=1e-7;
export function roomPolygon(room){if(room.shape==='custom')return room.vertices;const w=room.width,d=room.depth;return room.shape==='l-shape'?[{x:0,z:0},{x:w*.68,z:0},{x:w*.68,z:d*.3},{x:w,z:d*.3},{x:w,z:d},{x:0,z:d}]:[{x:0,z:0},{x:w,z:0},{x:w,z:d},{x:0,z:d}];}
export function signedArea(p){return p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a.x*b.z-b.x*a.z},0)/2;}
const cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);
function onSegment(p,a,b){return Math.abs(cross(a,b,p))<EPS&&p.x>=Math.min(a.x,b.x)-EPS&&p.x<=Math.max(a.x,b.x)+EPS&&p.z>=Math.min(a.z,b.z)-EPS&&p.z<=Math.max(a.z,b.z)+EPS;}
function intersections(a,b,c,d){const vx=b.x-a.x,vz=b.z-a.z,wx=d.x-c.x,wz=d.z-c.z,den=vx*wz-vz*wx;if(Math.abs(den)<EPS)return [];const t=((c.x-a.x)*wz-(c.z-a.z)*wx)/den,u=((c.x-a.x)*vz-(c.z-a.z)*vx)/den;return t>=-EPS&&t<=1+EPS&&u>=-EPS&&u<=1+EPS?[Math.max(0,Math.min(1,t))]:[];}
export function pointInside(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(onSegment(p,a,b))return true;if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)inside=!inside;}return inside;}
export function polygonIssue(poly){if(!Array.isArray(poly)||poly.length<3||poly.length>24||!poly.every(p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.z)))return 'Trace between 3 and 24 room corners.';for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if(Math.hypot(b.x-a.x,b.z-a.z)<.05)return 'Corners are too close together.';for(let j=i+1;j<poly.length;j++){if(j===i+1||(i===0&&j===poly.length-1))continue;const c=poly[j],d=poly[(j+1)%poly.length];if(intersections(a,b,c,d).length||onSegment(a,c,d)||onSegment(b,c,d)||onSegment(c,a,b)||onSegment(d,a,b))return 'The outline crosses itself. Trace around the perimeter in order.';}}if(Math.abs(signedArea(poly))<1)return 'The room outline is too small.';return null;}
export function containsPolygon(room,piece){if(!piece.every(p=>pointInside(p,room)))return false;for(let i=0;i<piece.length;i++){const a=piece[i],b=piece[(i+1)%piece.length],ts=[0,1];for(let j=0;j<room.length;j++)ts.push(...intersections(a,b,room[j],room[(j+1)%room.length]));ts.sort((a,b)=>a-b);for(let j=1;j<ts.length;j++){const t=(ts[j-1]+ts[j])/2;if(!pointInside({x:a.x+(b.x-a.x)*t,z:a.z+(b.z-a.z)*t},room))return false;}}return true;}
export function calibrateTrace(points,reference,feet){if(reference.length!==2||!Number.isFinite(feet)||feet<=0||feet>100)throw Error('Enter a known distance between 0 and 100 feet.');const pixels=Math.hypot(reference[1].x-reference[0].x,reference[1].z-reference[0].z);if(pixels<5)throw Error('Choose two distinct measurement points, farther apart.');if(!reference.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.z)))throw Error('Invalid measurement points.');const issue=polygonIssue(points);if(issue)throw Error(issue);const scale=feet/pixels,minX=Math.min(...points.map(p=>p.x)),minZ=Math.min(...points.map(p=>p.z));let vertices=points.map(p=>({x:+((p.x-minX)*scale).toFixed(4),z:+((p.z-minZ)*scale).toFixed(4)}));if(signedArea(vertices)<0)vertices.reverse();const width=Math.max(...vertices.map(p=>p.x)),depth=Math.max(...vertices.map(p=>p.z));if(width<4||depth<4||width>60||depth>60)throw Error('The traced room must be 4–60 feet across. Check the known measurement.');if(polygonIssue(vertices))throw Error(polygonIssue(vertices));return {shape:'custom',width,depth,vertices};}
export function walls(room){const p=roomPolygon(room);return p.map((a,i)=>{const b=p[(i+1)%p.length],length=Math.hypot(b.x-a.x,b.z-a.z);return {a,b,index:i,length,dx:(b.x-a.x)/length,dz:(b.z-a.z)/length};});}
export function attachmentIssue(room,item,others=[]){const wall=walls(room)[item.wall],height=room.height||8;if(!wall||!Number.isInteger(item.wall)||!['door','window','art'].includes(item.kind)||![item.offset,item.width,item.height,item.bottom].every(Number.isFinite))return 'Choose a wall and valid measurements.';if(item.width<.25||item.height<.25||item.offset<0||item.offset+item.width>wall.length+EPS||item.bottom<0||item.bottom+item.height>height+EPS)return 'Keep the entire opening or artwork inside the wall.';if(item.kind==='door'&&item.bottom!==0)return 'Doors start at floor level.';for(const other of others){if(other.id===item.id||other.wall!==item.wall)continue;if(item.offset<other.offset+other.width-EPS&&item.offset+item.width>other.offset+EPS&&item.bottom<other.bottom+other.height-EPS&&item.bottom+item.height>other.bottom+EPS)return 'That overlaps another opening or artwork on this wall.';}return null;}
export function validArchitecture(state){const r=state.room;if(r.height!==undefined&&(!Number.isFinite(r.height)||r.height<7||r.height>15))return false;if(r.shape==='custom'&&(polygonIssue(r.vertices)||signedArea(r.vertices)<=0||r.vertices.some(p=>p.x<0||p.z<0||p.x>r.width+EPS||p.z>r.depth+EPS)))return false;if(!Array.isArray(state.openings||[])||!Array.isArray(state.artworks||[]))return false;const entries=[...(state.openings||[]),...(state.artworks||[])];if(entries.length>24||new Set(entries.map(p=>p.id)).size!==entries.length)return false;return entries.every(p=>typeof p.id==='string'&&!attachmentIssue(r,p,entries)&&(p.kind!=='art'||((p.imageAspect===undefined||(Number.isFinite(p.imageAspect)&&p.imageAspect>0&&p.imageAspect<100))&&typeof p.image==='string'&&p.image.length<700000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(p.image))));}
